// src/games/wordScramble/wordDatabase.ts

export const WORD_DB = {
  // Niveau FACILE (Mots courants)
  easy: {
    4: ['CHAT', 'MONT','PAIN', 'LOUP', 'MAIN', 'PIED', 'ROSE', 'VERT', 'BLEU', 'LUNE', 'JOIE', 'PEUR', 'VENT', 'MER', 'CIEL', 'PLAN','FILM', 'JEUX', 'RIRE', 'FEUX', 'EAUX', 'BOIS', 'LACS', 'NUIT', 'JOUR',
        'PONT', 'SANG', 'PEAU', 'BRAS', 'DOS', 'POUX', 'OEUF', 'LOI', 'ROI'],
    5: ['ARBRE', 'LIVRE', 'POMME', 'CHIEN', 'LAPIN', 'TIGRE', 'PLUIE', 'NEIGE', 'TABLE', 'REINE', 'CHAISE', 'PORTE', 'ECOLE', 'STYLO', 'AVION','IMAGE', 'VOIX', 'GOÛT', 'FÊTE', 'PLAGE', 'FORÊT', 'FLEUR', 'HERBE', 'NUAGE', 
        'ETOILE', 'PLUIE', 'VENT', 'SABLE', 'ROCHER',],
    6: ['ANIMAL', 'MAISON', 'JARDIN', 'CAHIER', 'CRAYON', 'SOLEIL', 'NUAGE', 'OISEAU', 'BATEAU', 'VOITURE', 'LETTRE', 'AMOUR', 'ENFANT','JARDIN', 'AMITIÉ', 'RIVIÈRE', 'SAISON', 'MÉTIER', 'SORCIER', 'MAGIE', 'CHÂTEAU',
        'CHAMBRE', 'CUISINE', 'SALLE', 'ECOLE', 'BUREAU', 'USINE', 'FABRIQUE', 'MACHINE'],
    7: ['BONJOUR', 'FAMILLE', 'MUSIQUE', 'GUITARE', 'LIBERTE', 'SOURIRE', 'VOYAGE', 'JOURNAL', 'FROMAGE', 'CHOCOLAT','HORLOGE', 'FENETRE', 'PARCOURS', 'HISTOIRE', 'PERSONNE', 'MOMENT', 'SECONDE', 
        'MINUTE', 'HEURE', 'JOURNEE', 'SEMAINE', 'MOIS', 'ANNÉE', 'SIECLE']
  },
  
  // Niveau MOYEN (Vocabulaire étendu)
  medium: {
    6: ['PROJET', 'NATURE', 'OCEAN', 'DESERT', 'JUNGLE', 'PLANETE', 'ESPACE', 'ROBOT', 'ECRAN', 'SOURIS', 'CLAVIER', 'REVEIL','DÉFIS', 'OPTION', 'CAUSES', 'EFFETS', 'RÈGLES', 'PHASES', 'CYCLES', 'USAGES',
        'MODÈLES', 'IDÉALS', 'DÉBATS', 'DROITS', 'DEVOIRS', 'CHOIX', 'VOEUX', 'SOUHAITS'],
    7: ['SCIENCE', 'COURAGE', 'MYSTERE', 'MEMOIRE', 'HISTOIRE', 'THEATRE', 'CINEMA', 'CULTURE', 'SOCIETE', 'ECONOMIE','PROGRÈS', 'SYSTÈME', 'MÉTHODE', 'PROCESS', 'CONCEPT', 'IDÉAL', 'LOGIQUE', 
        'DÉBAT', 'PHASE', 'CYCLE', 'USAGE', 'MODÈLE', 'RÈGLE', 'CHOIX', 'DROIT'],
    8: ['SOLUTION', 'CREATION', 'AVENTURE', 'MONTAGNE', 'VACANCES', 'QUESTION', 'REPONSE', 'EXEMPLE', 'PROBLEME', 'RESULTAT', 'MILLENAIRE','ÉQUILIBRE', 'STRATÉGIE', 'FONCTION', 'POSITION', 'RELATION', 'CONTEXTE', 
        'ENVIRON', 'SITUATION', 'CONDITION', 'POSITION', 'NIVEAU', ]
  },
  
  // Niveau DIFFICILE (Mots complexes / abstraits)
  hard: {
    7: ['EMOTION', 'PASSION', 'SUCCESS', 'FATIGUE', 'MALADIE', 'DOCTEUR', 'HOPITAL', 'DENTISTE', 'PHARMACIE','ANALYSE', 'SYNTHÈSE', 'CRITIQUE', 'DIALOGUE', 'PARADOXE', 'THÉORIE', 
        'PRATIQUE', 'CONCEPT', 'ABSTRAIT', 'CONCRET','FORMEL'],
    8: ['STRATEGIE', 'POLITIQUE', 'INDUSTRIE', 'BATIMENT', 'IMMEUBLE', 'AEROPORT', 'CHAMPION', 'VICTOIRE','COMPLEXE', 'STRUCTURE', 'MÉCANIQUE', 'ÉLECTRIQUE', 'AUTOMATIQUE', 'NUMÉRIQUE',
        'VIRTUEL', 'ABSTRAIT', 'CONCRET', 'MATÉRIEL', 'IMMATÉRIEL'],
    9: ['PHENOMENE', 'EDUCATION', 'UNIVERSITE', 'PROFESSEUR', 'RECHERCHE', 'DECOUVERTE', 'INVENTION', 'EVOLUTION','TRANSITION', 'RÉVOLUTION', 'INNOVATION', 'APPLICATION', 'EXPÉRIENCE',
        'CONNAISSANCE', 'COMPÉTENCE', 'PERFORMANCE', 'DÉVELOPPEMENT', 'PROGRESSION']
  },
  
  // Niveau MAÎTRE (Expert)
  master: {
    8: ['PARADOXE','MUSICAL', 'CINÉMATO', 'THÉÂTRAL','SYNTHESE', 'ANALYSE', 'CRITIQUE', 'ARGUMENT', 'DIALOGUE','ALGORITHME', 'VARIABLE', 'FONCTION', 'ÉQUATION', 'THÉORÈME', 'POSTULAT',
        'AXIOME', 'DÉFINITION', 'PROPOSITION', 'HYPOTHÈSE', 'CONJECTURE'],
    9: ['COMPLEXE', 'STRUCTURE', 'FONCTION', 'MECANIQUE', 'ELECTRIQUE', 'AUTOMATIQUE','GÉOGRAPHIE', 'HISTORIQUE', 'TECHNIQUE', 'SCIENTIFIQUE', 'ARTISTIQUE',
        'LITTÉRAIRE',   'PHOTOGRAPHIQUE'],
    10: ['PHILOSOPHIE','GESTION', 'MANAGEMENT', 'DIRECTION', 'COORDINATION','INTERNATIONAL','PSYCHOLOGIE', 'SOCIOLOGIE', 'ARCHEOLOGIE', 'ASTRONOMIE', 'LITTERATURE', 'MATHEMATIQUES', 'STATISTIQUES','BIOLOGIQUE', 'CHIMIQUE', 'PHYSIQUE', 'ÉCONOMIQUE', 'POLITIQUE', 'CULTURELLE',
         'SOCIALE', 'HUMAINE', 'UNIVERSELLE', 'PARTICULIÈRE', 'GÉNÉRALE', 'SPÉCIFIQUE','INFORMATIQUE', 'TECHNOLOGIE', 'COMMUNICATION', 'ORGANISATION', 'ADMINISTRATION',
          'ENVIRONNEMENT', 'DÉVELOPPEMENT', 'CONSTITUTION', 'INSTITUTION',
         'ORGANISATION', 'ASSOCIATION', 'FONDATION', 'ENTREPRISE', 'COOPÉRATIVE']
  }
};