// src/games/wordScramble/wordDatabase.ts

export const WORD_DB = {
  // Niveau FACILE (Mots courants)
  easy: {
    4: ['CHAT', 'PAIN', 'LOUP', 'MAIN', 'PIED', 'ROSE', 'VERT', 'BLEU', 'LUNE', 'JOIE', 'PEUR', 'VENT', 'MER', 'CIEL', 'PLAN'],
    5: ['ARBRE', 'LIVRE', 'POMME', 'CHIEN', 'LAPIN', 'TIGRE', 'PLUIE', 'NEIGE', 'TABLE', 'CHAISE', 'PORTE', 'ECOLE', 'STYLO', 'AVION'],
    6: ['ANIMAL', 'MAISON', 'JARDIN', 'CAHIER', 'CRAYON', 'SOLEIL', 'NUAGE', 'OISEAU', 'BATEAU', 'VOITURE', 'LETTRE', 'AMOUR', 'ENFANT'],
    7: ['BONJOUR', 'FAMILLE', 'MUSIQUE', 'GUITARE', 'LIBERTE', 'SOURIRE', 'VOYAGE', 'JOURNAL', 'FROMAGE', 'CHOCOLAT']
  },
  
  // Niveau MOYEN (Vocabulaire étendu)
  medium: {
    6: ['PROJET', 'NATURE', 'OCEAN', 'DESERT', 'JUNGLE', 'PLANETE', 'ESPACE', 'ROBOT', 'ECRAN', 'SOURIS', 'CLAVIER', 'REVEIL'],
    7: ['SCIENCE', 'COURAGE', 'MYSTERE', 'MEMOIRE', 'HISTOIRE', 'THEATRE', 'CINEMA', 'CULTURE', 'SOCIETE', 'ECONOMIE'],
    8: ['SOLUTION', 'CREATION', 'AVENTURE', 'MONTAGNE', 'VACANCES', 'QUESTION', 'REPONSE', 'EXEMPLE', 'PROBLEME', 'RESULTAT']
  },
  
  // Niveau DIFFICILE (Mots complexes / abstraits)
  hard: {
    7: ['EMOTION', 'PASSION', 'SUCCESS', 'FATIGUE', 'MALADIE', 'DOCTEUR', 'HOPITAL', 'DENTISTE', 'PHARMACIE'],
    8: ['STRATEGIE', 'POLITIQUE', 'INDUSTRIE', 'BATIMENT', 'IMMEUBLE', 'AEROPORT', 'CHAMPION', 'VICTOIRE'],
    9: ['PHENOMENE', 'EDUCATION', 'UNIVERSITE', 'PROFESSEUR', 'RECHERCHE', 'DECOUVERTE', 'INVENTION', 'EVOLUTION']
  },
  
  // Niveau MAÎTRE (Expert)
  master: {
    8: ['PARADOXE', 'SYNTHESE', 'ANALYSE', 'CRITIQUE', 'ARGUMENT', 'DIALOGUE'],
    9: ['COMPLEXE', 'STRUCTURE', 'FONCTION', 'MECANIQUE', 'ELECTRIQUE', 'AUTOMATIQUE'],
    10: ['PHILOSOPHIE', 'PSYCHOLOGIE', 'SOCIOLOGIE', 'ARCHEOLOGIE', 'ASTRONOMIE', 'LITTERATURE', 'MATHEMATIQUES', 'STATISTIQUES']
  }
};